theme: jekyll-theme-cayman
title: Introdução a Algoritmos com Portugol Studio

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
